### ISSUE TITLE
Fresnel and Fraunhofer beam propagator with a test routine

### ISSUE THREAD

**Issue by kunguz** [kunguz/odak#1]
Recently, a beam propagator is added to `Odak`, which contains Fresnel Impulse Response (FIR), Fresnel Tranfer Function (FTF), and Fraunhofer propagation routines. They are all added to `odak.wave.classical` script that can be found in [here](https://github.com/kunguz/odak/blob/master/odak/wave/classical.py#L3).

A test routine is also added accordingly as in [here](https://github.com/kunguz/odak/blob/master/test/test_beam_propagation.py).

The outcome of the test routine can be visualize as follows:
Initial field:
![resim](https://user-images.githubusercontent.com/191201/97921712-30c79300-1d10-11eb-8abb-356202ab5e11.png)
Propagated field:
![resim](https://user-images.githubusercontent.com/191201/97921771-4c329e00-1d10-11eb-8634-c4ef007d4754.png)
Back propagated field at the source:
![resim](https://user-images.githubusercontent.com/191201/97921837-610f3180-1d10-11eb-8343-5ae42b4ef719.png)

and here is a visualization of the same code with a sample image:
Initial field:
![resim](https://user-images.githubusercontent.com/191201/97921934-8734d180-1d10-11eb-9957-ae5a5e5d30a8.png)
Propagated field:
![resim](https://user-images.githubusercontent.com/191201/97921971-93b92a00-1d10-11eb-9c4c-4c1fd69ea0f1.png)
Back propagated field at the source:
![resim](https://user-images.githubusercontent.com/191201/97922023-a92e5400-1d10-11eb-95ff-7b3fb570695e.png)

**Comment by askaradeniz** [comment]
Thanks for adding this feature.

Another example result of Fresnel propagation:

Initial field:
![img](https://user-images.githubusercontent.com/50996598/98051963-0a0b7880-1e46-11eb-9a73-f10edf22c3a3.png)

Propagated field:
![hologram](https://user-images.githubusercontent.com/50996598/98051979-1394e080-1e46-11eb-953b-0c471d2fbe56.png)

Reconstructed field:
![reconstruction](https://user-images.githubusercontent.com/50996598/98051992-1b548500-1e46-11eb-9e0b-d1db97ba997c.png)

However, I had to flip the image vertically to get the results in the right direction. I read the image with opencv and set the sample field as the following.
```
img = cv2.imread("0886.png")
sample_field[:,:] = img[::-1,:,0]
```

**Comment by kunguz** [comment]
This means I can close the issue.

**Comment by kunguz** [comment]
@askaradeniz I forgot to mention about this. Odak has also built in toolkit for basic things such as image loading: https://github.com/kunguz/odak/blob/master/odak/tools/file.py#L59
