### ISSUE TITLE
Adding Stochastic Gradient Descent based hologram calculation

### ISSUE THREAD

**Issue by kunguz** [kunguz/odak#21]
Odak supports `torch` based hologram calculation routines. `Odak.learn.wave` lacks a definition that can calculate holograms using `Stochastic Gradient Descent`. The latest and greatest in combining `torch` and `odak` is at a branch called `torch_1_8_0`. At the time of the writing of this issue, any development should go on top of that branch.

- [x] Add a `stochastic_gradient_descent` definition to `odak.learn.wave.classical`.
- [x] Add a test script to `test` folder to run a test for the new added `stochastic_gradient_descent` definition.

**Comment by KorayKavakli** [comment]
Issue #22 resolves the case.

**Comment by kunguz** [comment]
Adding @askaradeniz for visibility, and closing the issue. Thanks @KorayKavakli !
