### ISSUE TITLE
[Feature Request] Add `.pre-commit-config.yml`

### ISSUE THREAD

**Issue by SauravMaheshkar** [kunguz/odak#36]
I noticed that most of (if not all) the steps of the Contributing wiki can be automated via [**pre-commit**](https://pre-commit.com/). Having [**pre-commit**](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

**Comment by kunguz** [comment]
Hi Saurav, Thank you for reaching out and showing interest in our work. 

Pre-commit seems like a good feature that we can take advantage of. Perhaps, in this case, a good starting point is to go with a pull request.

I look forward to hearing from you.

Kaan

**Comment by kunguz** [comment]
Saurav, unfortunately, I wasn't aware that the `requirements.txt` has to grow in size to support `precommit`. At this time, this falls out of our future planning with regards to having a shorter list at `requirements.txt`. I will go ahead and close this issue and will label it as `wontfix`.

**Comment by SauravMaheshkar** [comment]
Alright. Thanks for the explanation @kunguz
