### ISSUE TITLE
Gerchberg Saxton bug

### ISSUE THREAD

**Issue by jsreddy** [kunguz/odak#40]
https://github.com/kunguz/odak/blob/c8af57e0ed6fcda579762eeeec43e071384921f6/odak/learn/wave/classical.py#L290

I believe there is a bug in the GS pytorch version 
Shouldn't the amplitude be set from `reconstruction` rather than `hologram`?

**Comment by kunguz** [comment]
You are right. Please have a pull request so thatwe can incorporate it in the next version. Thanks!

**Comment by kunguz** [comment]
9df3b6a3cc9a4c005586a133161be55e85b94a80 resolves the issue. Please do not hesitate to reopen the issue if the problem persists. Please make sure to use `odak` from the repository but not from `pip` as this change will not be reflected in `pip` until we release `odak 0.2.0`. Thanks!

**Comment by kunguz** [comment]
odak is now at 0.2.0
