### ISSUE TITLE
Migrating learn submodule to pytorch 1.8.0

### ISSUE THREAD

**Issue by askaradeniz** [kunguz/odak#6]
Currently, some methods used in the `learn` submodule uses external functions for some operations. The current list of these functions is as the following:

- `fftshift` in `toolkit.py`
- `ifftshift` in `toolkit.py`

These functions are included in [fft](https://pytorch.org/docs/master/fft.html) module in pytorch 1.8.0. We can update these functions when pytorch 1.8.0 becomes stable.

**Comment by kunguz** [comment]
As a side note and a future reminder, starting from `1.8.0`, torch will have a new [torch.fft submodule]() as indicated in these warnings from torch `1.7.0`:

```shell
UserWarning: The function torch.ifft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.ifft or torch.fft.ifftn.

UserWarning: The function torch.fft is deprecated and will be removed in PyTorch 1.8. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.fftn.
```

**Comment by kunguz** [comment]
also `fftn` has to be replaced with `fft2` in the future.

**Comment by kunguz** [comment]
Odak has a new brach called `torch_1_8_0` in which `odak/learn/wave/toolkit.py` is removed and routines are updated for `Torch 1.8.0`.

**Comment by kunguz** [comment]
`Torch 1.8.0`, first release candidate is announced 2-3 days ago. We should expect to have the new `torch` in the next 20-30 days. Then I will be able to merge and close this issue.

**Comment by kunguz** [comment]
3123057e687e86c9882bbce5e8568be5da4fecb6 resolves the case.
